# Support the author by using the funding link below
# Developed and maintained by Ben Adams
# Buy Me a Coffee: https://buymeacoffe.com/thnkfstr

buy_me_a_coffee: thnkfstr

# Your support means a lot and helps me continue the development of an open source project like this.